openapi: 3.0.0
info:
  title: NodeJS Project
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:3000/
    description: local server
  - url: http://producation.app/api
    description: production server
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
              example:
                username: nina
                password: nina
      responses:
        '201':
          description: Created

  /band-members:
    get:
      tags:
        - Band Members
      security:
        - bearerAuth: []  
      responses:
        '200': 
          description: Returns a list of band members.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id: 
                      type: string
                    name: 
                      type: string
                    instrument: 
                      type: string
                    orbitLength: 
                      type: number
                    color: 
                      type: string
                    biography: 
                      type: string
                  example:
                    _id: 62b86377ad93686e784f8ea2
                    name: nina
                    instrument: kkk
                    orbitLength: 42
                    color: '#453454'
                    biography: biography

                  
                    
  /band-member/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Band Member ID
      tags:
        - Band Members
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns band member's detailed information.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  bandMember:
                    type: object
                    properties:
                      name: 
                        type: string
                      instrument: 
                        type: string
                      orbitLength: 
                        type: number
                      color: 
                        type: string
                      biography: 
                        type: string
              example:
                bandMember:
                  _id: 62b86377ad93686e784f8ea2
                  name: nina
                  instrument: kkk
                  orbitLength: 42
                  color: '#453454'
                  biography: biography
                    

  /new-member:
    post:
      tags:
        - Band Members
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitLength:
                  type: string
                color:
                  type: string
                biography:
                  type: string
              required:
                - name
                - instrument
                - orbitLength
                - color
                - biography
              example:
                name: nina
                instrument: kkk
                orbitLength: 42
                color: '#453454'
                biography: biography
      responses:
        '201':
          description: Created

  
  /edit-member/{id}:
     patch:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: The band member ID
      tags:
        - Band Members
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitLength:
                  type: string
                color:
                  type: string
                biography:
                  type: string
              required:
                - name
                - instrument
                - orbitLength
                - color
                - biography
              example:
                name: nina
                instrument: kkk
                orbitLength: 42
                color: '#453454'
                biography: biography
      responses:
        '200':
          description: updated
  
  /delete-member/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: The band member ID
      tags:
        - Band Members
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Deleted

#

  /social-media:
    get:
      tags:
        - Social Media
      security:
        - bearerAuth: []  
      responses:
        '200': 
          description: Returns a list of social media.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    name: 
                      type: string
                    url: 
                      type: string
                  example:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
                   

                  
                    
  /social-media/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Social Media id
      tags:
        - Social Media
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns social media's detailed information.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  socialLink:
                    type: object
                    properties:
                      name: 
                        type: string
                      url: 
                        type: string
              example:
                socialLink:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
                    

  /add-social:
    post:
      tags:
        - Social Media
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
              required:
                - name
                - url
              example:
                socialLink:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
      responses:
        '201':
          description: Created

  
  /edit-social/{id}:
     patch:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: The social media ID
      tags:
        - Social Media
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
              required:
                - name
                - url
              example:
                socialLink:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    name: facebook
                    url: https://www.facebook.com/
      responses:
        '200':
          description: updated
  
  /delete-social:
    delete:
      tags:
        - Social Media
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
              example:
                id: 62a3372b61d0d7839c1cb687
      responses:
        '200':
          description: Deleted


  /about-band/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: Band id
      tags:
        - About Band
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Returns band's detailed information.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  socialLink:
                    type: object
                    properties:
                      about: 
                        type: string
              example:
                band:
                    _id: 62b88c20f75abbb01ab2f5b5
                    about: this is a good band
